---
- name: Create /etc/systemd/system/nginx.service.d for systemd
  file:
     name=/etc/systemd/system/nginx.service.d
     state=directory
     owner=root
     group=root
     mode=0755
  tags: [ "nginx", "nginx_install" ]

- name: Configure limits for CentOS 7
  template:
    src=systemd-limits.conf.j2
    dest=/etc/systemd/system/nginx.service.d/limits.conf
    owner=root
    group=root
    mode=0644
  tags: [ "nginx", "nginx_install" ]
